Databases:
  BP: ../training_database/wavs/{uri}.wav

Protocols:
  BP:
    SpeakerDiarization:
      VlaamseAudio:
        scope: file
        train:
          uri: "../training_database/lists/train.lst"
          annotation: "../training_database/rttms/train.rttm"
          annotated: "../training_database/uems/train.uem"
        development:
          uri: "../training_database/lists/development.lst"
          annotation: "../training_database/rttms/train.rttm"
          annotated: "../training_database/uems/train.uem"
        test:
          uri: "../training_database/lists/test.lst"
          annotation: "../training_database/rttms/train.rttm"
          annotated: "../training_database/uems/train.uem"
        