Databases:
  BP: 
  - ../training_database/wavs/{uri}.wav

Protocols:
  BP:
    SpeakerDiarization:
      VlaamseAudio:
        scope: file
        train:
          uri: ../training_database/lists/train.lst
          annotation: ../training_database/rttms/train.rttm
          annotated: ../training_database/uems/train.uem
        development:
          uri: ../training_database/lists/development.lst
          annotation: ../training_database/rttms/development.rttm
          annotated: ../training_database/uems/development.uem
        test:
          uri: ../training_database/lists/test.lst
          annotation: ../training_database/rttms/test.rttm
          annotated: ../training_database/uems/test.uem
        