version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: C:/Users/verho/Documents/School/2024-2025/Bacherlorproef/bp-stemmen-onderscheiden/executable/pipeline/embedding/pytorch_model.bin
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: C:/Users/verho/Documents/School/2024-2025/Bacherlorproef/bp-stemmen-onderscheiden/executable/pipeline/segmentation/pytorch_model.bin
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
